"""add pages and links pages

Revision ID: 112ea99078cd
Revises: 
Create Date: 2025-11-30 15:57:27.582813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '112ea99078cd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pages',
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('length_chars', sa.Integer(), nullable=True),
    sa.Column('num_editors', sa.Integer(), nullable=True),
    sa.Column('num_revisions', sa.Integer(), nullable=True),
    sa.Column('links_out_count', sa.Integer(), nullable=True),
    sa.Column('links_in_count', sa.Integer(), nullable=True),
    sa.Column('pagerank_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('page_id')
    )
    op.create_table('links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_page_id', sa.Integer(), nullable=False),
    sa.Column('target_page_id', sa.Integer(), nullable=False),
    sa.Column('anchor_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['source_page_id'], ['pages.page_id'], ),
    sa.ForeignKeyConstraint(['target_page_id'], ['pages.page_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('links')
    op.drop_table('pages')
    # ### end Alembic commands ###
